# docker-compose.yml (for development)
services:
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: O43bNVSHlnb6r4DUOGuI
    networks:
      - app-network

  web:
    build:
      context: .
      args:
        SECRET_KEY: ${SECRET_KEY}
        DEBUG: ${DEBUG}
        DATABASE_URL: ${DATABASE_URL}
    command: gunicorn job_tracker.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - ./envs/development.env
    depends_on:
      - db
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
